name: npm-release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: publish
        run: |
          cd package
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish --access=public
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
